### PR TITLE
Java16 ladvace lint & style fix

### PR DESCRIPTION
**Pull request by Eskaan**
## Before
Bildschirmfoto 2021-08-03 um 15 27 58
Bildschirmfoto 2021-08-03 um 15 28 05
## After
Bildschirmfoto 2021-08-03 um 15 28 26
Bildschirmfoto 2021-08-03 um 15 29 13

Additionaly also a lint fix (you removed the instagram and facebook links, I think by accident)

### CODE REVIEW

**Comment by Eskaan** [comment]
f898cb1 New function output was preventing start-check from working correctly

**Comment by Ladvace** [comment]
could you fix this pls
image

**Comment by Eskaan** [comment]
> could you fix this pls
> image

The problem is, that I merged the Dependency updates from upstream

**Comment by Ladvace** [comment]
> > could you fix this pls
> > image
> 
> The problem is, that I merged the Dependency updates from upstream

**Comment by Ladvace** [comment]
> > could you fix this pls
> > image
> 
> The problem is, that I merged the Dependency updates from upstream

start the pr from my branch, or try fixing this otherwise this is going to be pushed even in the master

**Comment by Eskaan** [comment]
Okay, will take a moment

**Pull request closed without merging**
